-- SPDX-License-Identifier: AGPL-3.0-or-later
-- Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
||| Deterministic declaration renderer for the accelerator ABI.
|||
||| Idris2 0.7 has no `c-header` code generator. This executable renders the
||| declarations directly from the typed constants governed by
||| `Abi.Accelerator`; the repository gate compares its output byte-for-byte.

module Abi.Generate

import Abi.Accelerator
import System

%default total

private
generatedNotice : String
generatedNotice = "Generated by Abi.Generate from the typechecked Idris2 ABI. DO NOT EDIT."

private
codesC : String
codesC =
  "#define ENACTION_ACCEL_ABI_MAJOR " ++ show abiMajor ++ "u\n" ++
  "#define ENACTION_ACCEL_ABI_MINOR " ++ show abiMinor ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_MAJOR " ++ show operationMajor ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_MINOR " ++ show operationMinor ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_FIXED_I32_DOT " ++ show (operationCode FixedI32Dot) ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_FIXED_I32_MATMUL " ++ show (operationCode FixedI32MatMul) ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_TENSOR_F32_RELU " ++ show (operationCode TensorF32Relu) ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_TENSOR_F32_RELU6 " ++ show (operationCode TensorF32Relu6) ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_TENSOR_F32_MATMUL " ++ show (operationCode TensorF32MatMul) ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_TENSOR_F32_ADD " ++ show (operationCode TensorF32Add) ++ "u\n" ++
  "#define ENACTION_ACCEL_OPERATION_TENSOR_F32_MUL " ++ show (operationCode TensorF32Mul) ++ "u\n" ++
  "#define ENACTION_ACCEL_LAYOUT_DOT " ++ show (layoutCode DotLayout) ++ "u\n" ++
  "#define ENACTION_ACCEL_LAYOUT_MATMUL " ++ show (layoutCode MatMulLayout) ++ "u\n" ++
  "#define ENACTION_ACCEL_LAYOUT_VECTOR " ++ show (layoutCode VectorLayout) ++ "u\n" ++
  "#define ENACTION_ACCEL_LANE_AUTHORITATIVE " ++ show (laneCode Authoritative) ++ "u\n" ++
  "#define ENACTION_ACCEL_LANE_ADVISORY " ++ show (laneCode Advisory) ++ "u\n" ++
  "#define ENACTION_ACCEL_LANE_REMOTE_JOB " ++ show (laneCode RemoteJob) ++ "u\n" ++
  "#define ENACTION_ACCEL_DETERMINISM_ADVISORY_ONLY " ++ show (determinismCode AdvisoryOnly) ++ "u\n" ++
  "#define ENACTION_ACCEL_DETERMINISM_TOLERANCE_BOUNDED " ++ show (determinismCode ToleranceBounded) ++ "u\n" ++
  "#define ENACTION_ACCEL_DETERMINISM_CANONICAL_EXACT " ++ show (determinismCode CanonicalExact) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_DECLARED " ++ show (supportCode Declared) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_DISCOVERABLE " ++ show (supportCode Discoverable) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_LOADABLE " ++ show (supportCode Loadable) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_RUNNABLE " ++ show (supportCode Runnable) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_CONFORMANT " ++ show (supportCode Conformant) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_RESILIENT " ++ show (supportCode Resilient) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_DETERMINISTIC " ++ show (supportCode Deterministic) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_BENCHMARKED " ++ show (supportCode Benchmarked) ++ "u\n" ++
  "#define ENACTION_ACCEL_SUPPORT_PRODUCTION_SUPPORTED " ++ show (supportCode ProductionSupported) ++ "u\n" ++
  "#define ENACTION_ACCEL_DEVICE_CPU " ++ show (deviceCode Cpu) ++ "u\n" ++
  "#define ENACTION_ACCEL_BACKEND_ZIG_SCALAR 1u\n" ++
  "#define ENACTION_ACCEL_STATUS_OK " ++ show (statusCode StatusOk) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_NULL_POINTER " ++ show (statusCode NullPointer) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_UNSUPPORTED_ABI " ++ show (statusCode UnsupportedAbi) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_UNSUPPORTED_OPERATION_VERSION " ++ show (statusCode UnsupportedOperationVersion) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_UNKNOWN_OPERATION " ++ show (statusCode UnknownOperation) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_INVALID_LANE " ++ show (statusCode InvalidLane) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_INVALID_SUPPORT " ++ show (statusCode InvalidSupport) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_INVALID_DETERMINISM " ++ show (statusCode InvalidDeterminism) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_LAYOUT_MISMATCH " ++ show (statusCode LayoutMismatch) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_LENGTH_MISMATCH " ++ show (statusCode LengthMismatch) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_DIMENSION_OVERFLOW " ++ show (statusCode DimensionOverflow) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_ARITHMETIC_OVERFLOW " ++ show (statusCode ArithmeticOverflow) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_INVALID_RESERVED_FIELD " ++ show (statusCode InvalidReservedField) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_UNSUPPORTED_REQUIREMENT " ++ show (statusCode UnsupportedRequirement) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_INDEX_OUT_OF_RANGE " ++ show (statusCode IndexOutOfRange) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_ALIASING_VIOLATION " ++ show (statusCode AliasingViolation) ++ "u\n" ++
  "#define ENACTION_ACCEL_STATUS_NON_FINITE_INPUT " ++ show (statusCode NonFiniteInput) ++ "u\n"

public export
cHeader : String
cHeader =
  "/* SPDX-License-Identifier: AGPL-3.0-or-later */\n" ++
  "/* " ++ generatedNotice ++ " */\n" ++
  "#ifndef ENACTION_ACCELERATOR_H\n#define ENACTION_ACCELERATOR_H\n\n" ++
  "#include <stdint.h>\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n" ++
  codesC ++ "\n" ++
  "typedef struct enaction_accel_request {\n" ++
  "  uint16_t abi_major; uint16_t abi_minor;\n" ++
  "  uint16_t operation_major; uint16_t operation_minor;\n" ++
  "  uint32_t operation; uint32_t lane;\n" ++
  "  uint32_t minimum_support; uint32_t minimum_determinism;\n" ++
  "  uint32_t layout; uint32_t reserved;\n" ++
  "  uint64_t dim0; uint64_t dim1; uint64_t dim2;\n" ++
  "} enaction_accel_request;\n\n" ++
  "typedef struct enaction_accel_buffer_i32 { const int32_t *data; uint64_t len; } enaction_accel_buffer_i32;\n" ++
  "typedef struct enaction_accel_buffer_i64 { int64_t *data; uint64_t len; } enaction_accel_buffer_i64;\n\n" ++
  "typedef struct enaction_accel_buffer_f32_in { const float *data; uint64_t len; } enaction_accel_buffer_f32_in;\n" ++
  "typedef struct enaction_accel_buffer_f32_out { float *data; uint64_t len; } enaction_accel_buffer_f32_out;\n\n" ++
  "typedef struct enaction_accel_capability {\n" ++
  "  uint16_t abi_major; uint16_t abi_minor;\n" ++
  "  uint16_t operation_major; uint16_t operation_minor;\n" ++
  "  uint32_t operation; uint32_t support; uint32_t determinism;\n" ++
  "  uint32_t backend_id; uint32_t device_class; uint32_t flags;\n" ++
  "} enaction_accel_capability;\n\n" ++
  "typedef struct enaction_accel_evidence {\n" ++
  "  uint16_t abi_major; uint16_t abi_minor;\n" ++
  "  uint16_t operation_major; uint16_t operation_minor;\n" ++
  "  uint32_t operation; uint32_t backend_id;\n" ++
  "  uint32_t support; uint32_t determinism;\n" ++
  "} enaction_accel_evidence;\n\n" ++
  "uint32_t enaction_accel_abi_version(void);\n" ++
  "uint32_t enaction_accel_capability_count(void);\n" ++
  "uint32_t enaction_accel_capability_at(uint32_t index, enaction_accel_capability *out);\n" ++
  "uint32_t enaction_accel_execute(const enaction_accel_request *request, const enaction_accel_buffer_i32 *left, const enaction_accel_buffer_i32 *right, enaction_accel_buffer_i64 *output, enaction_accel_evidence *evidence);\n\n" ++
  "uint32_t enaction_accel_execute_f32(const enaction_accel_request *request, const enaction_accel_buffer_f32_in *input, enaction_accel_buffer_f32_out *output, enaction_accel_evidence *evidence);\n\n" ++
  "uint32_t enaction_accel_execute_f32_binary(const enaction_accel_request *request, const enaction_accel_buffer_f32_in *left, const enaction_accel_buffer_f32_in *right, enaction_accel_buffer_f32_out *output, enaction_accel_evidence *evidence);\n\n" ++
  "#ifdef __cplusplus\n}\n#endif\n\n#endif\n"

private
codesZig : String
codesZig =
  "pub const abi_major: u16 = " ++ show abiMajor ++ ";\n" ++
  "pub const abi_minor: u16 = " ++ show abiMinor ++ ";\n" ++
  "pub const operation_major: u16 = " ++ show operationMajor ++ ";\n" ++
  "pub const operation_minor: u16 = " ++ show operationMinor ++ ";\n" ++
  "pub const operation_fixed_i32_dot: u32 = " ++ show (operationCode FixedI32Dot) ++ ";\n" ++
  "pub const operation_fixed_i32_matmul: u32 = " ++ show (operationCode FixedI32MatMul) ++ ";\n" ++
  "pub const operation_tensor_f32_relu: u32 = " ++ show (operationCode TensorF32Relu) ++ ";\n" ++
  "pub const operation_tensor_f32_relu6: u32 = " ++ show (operationCode TensorF32Relu6) ++ ";\n" ++
  "pub const operation_tensor_f32_matmul: u32 = " ++ show (operationCode TensorF32MatMul) ++ ";\n" ++
  "pub const operation_tensor_f32_add: u32 = " ++ show (operationCode TensorF32Add) ++ ";\n" ++
  "pub const operation_tensor_f32_mul: u32 = " ++ show (operationCode TensorF32Mul) ++ ";\n" ++
  "pub const layout_dot: u32 = " ++ show (layoutCode DotLayout) ++ ";\n" ++
  "pub const layout_matmul: u32 = " ++ show (layoutCode MatMulLayout) ++ ";\n" ++
  "pub const layout_vector: u32 = " ++ show (layoutCode VectorLayout) ++ ";\n" ++
  "pub const lane_authoritative: u32 = " ++ show (laneCode Authoritative) ++ ";\n" ++
  "pub const lane_advisory: u32 = " ++ show (laneCode Advisory) ++ ";\n" ++
  "pub const lane_remote_job: u32 = " ++ show (laneCode RemoteJob) ++ ";\n" ++
  "pub const determinism_advisory_only: u32 = " ++ show (determinismCode AdvisoryOnly) ++ ";\n" ++
  "pub const determinism_tolerance_bounded: u32 = " ++ show (determinismCode ToleranceBounded) ++ ";\n" ++
  "pub const determinism_canonical_exact: u32 = " ++ show (determinismCode CanonicalExact) ++ ";\n" ++
  "pub const support_declared: u32 = " ++ show (supportCode Declared) ++ ";\n" ++
  "pub const support_resilient: u32 = " ++ show (supportCode Resilient) ++ ";\n" ++
  "pub const support_deterministic: u32 = " ++ show (supportCode Deterministic) ++ ";\n" ++
  "pub const support_production_supported: u32 = " ++ show (supportCode ProductionSupported) ++ ";\n" ++
  "pub const device_cpu: u32 = " ++ show (deviceCode Cpu) ++ ";\n" ++
  "pub const backend_zig_scalar: u32 = 1;\n" ++
  "pub const status_ok: u32 = " ++ show (statusCode StatusOk) ++ ";\n" ++
  "pub const status_null_pointer: u32 = " ++ show (statusCode NullPointer) ++ ";\n" ++
  "pub const status_unsupported_abi: u32 = " ++ show (statusCode UnsupportedAbi) ++ ";\n" ++
  "pub const status_unsupported_operation_version: u32 = " ++ show (statusCode UnsupportedOperationVersion) ++ ";\n" ++
  "pub const status_unknown_operation: u32 = " ++ show (statusCode UnknownOperation) ++ ";\n" ++
  "pub const status_invalid_lane: u32 = " ++ show (statusCode InvalidLane) ++ ";\n" ++
  "pub const status_invalid_support: u32 = " ++ show (statusCode InvalidSupport) ++ ";\n" ++
  "pub const status_invalid_determinism: u32 = " ++ show (statusCode InvalidDeterminism) ++ ";\n" ++
  "pub const status_layout_mismatch: u32 = " ++ show (statusCode LayoutMismatch) ++ ";\n" ++
  "pub const status_length_mismatch: u32 = " ++ show (statusCode LengthMismatch) ++ ";\n" ++
  "pub const status_dimension_overflow: u32 = " ++ show (statusCode DimensionOverflow) ++ ";\n" ++
  "pub const status_arithmetic_overflow: u32 = " ++ show (statusCode ArithmeticOverflow) ++ ";\n" ++
  "pub const status_invalid_reserved_field: u32 = " ++ show (statusCode InvalidReservedField) ++ ";\n" ++
  "pub const status_unsupported_requirement: u32 = " ++ show (statusCode UnsupportedRequirement) ++ ";\n" ++
  "pub const status_index_out_of_range: u32 = " ++ show (statusCode IndexOutOfRange) ++ ";\n" ++
  "pub const status_aliasing_violation: u32 = " ++ show (statusCode AliasingViolation) ++ ";\n" ++
  "pub const status_non_finite_input: u32 = " ++ show (statusCode NonFiniteInput) ++ ";\n"

public export
zigDeclarations : String
zigDeclarations =
  "// SPDX-License-Identifier: AGPL-3.0-or-later\n" ++
  "// " ++ generatedNotice ++ "\n\n" ++ codesZig ++ "\n" ++
  "pub const Request = extern struct {\n" ++
  "    abi_major: u16, abi_minor: u16, operation_major: u16, operation_minor: u16,\n" ++
  "    operation: u32, lane: u32, minimum_support: u32, minimum_determinism: u32,\n" ++
  "    layout: u32, reserved: u32, dim0: u64, dim1: u64, dim2: u64,\n};\n" ++
  "pub const BufferI32 = extern struct { data: ?[*]const i32, len: u64 };\n" ++
  "pub const BufferI64 = extern struct { data: ?[*]i64, len: u64 };\n" ++
  "pub const BufferF32In = extern struct { data: ?[*]const f32, len: u64 };\n" ++
  "pub const BufferF32Out = extern struct { data: ?[*]f32, len: u64 };\n" ++
  "pub const Capability = extern struct {\n" ++
  "    abi_major: u16, abi_minor: u16, operation_major: u16, operation_minor: u16,\n" ++
  "    operation: u32, support: u32, determinism: u32, backend_id: u32, device_class: u32, flags: u32,\n};\n" ++
  "pub const Evidence = extern struct {\n" ++
  "    abi_major: u16, abi_minor: u16, operation_major: u16, operation_minor: u16,\n" ++
  "    operation: u32, backend_id: u32, support: u32, determinism: u32,\n};\n"

private
codesRust : String
codesRust =
  "pub const ABI_MAJOR: u16 = " ++ show abiMajor ++ ";\n" ++
  "pub const ABI_MINOR: u16 = " ++ show abiMinor ++ ";\n" ++
  "pub const OPERATION_MAJOR: u16 = " ++ show operationMajor ++ ";\n" ++
  "pub const OPERATION_MINOR: u16 = " ++ show operationMinor ++ ";\n" ++
  "pub const OPERATION_FIXED_I32_DOT: u32 = " ++ show (operationCode FixedI32Dot) ++ ";\n" ++
  "pub const OPERATION_FIXED_I32_MATMUL: u32 = " ++ show (operationCode FixedI32MatMul) ++ ";\n" ++
  "pub const OPERATION_TENSOR_F32_RELU: u32 = " ++ show (operationCode TensorF32Relu) ++ ";\n" ++
  "pub const OPERATION_TENSOR_F32_RELU6: u32 = " ++ show (operationCode TensorF32Relu6) ++ ";\n" ++
  "pub const OPERATION_TENSOR_F32_MATMUL: u32 = " ++ show (operationCode TensorF32MatMul) ++ ";\n" ++
  "pub const OPERATION_TENSOR_F32_ADD: u32 = " ++ show (operationCode TensorF32Add) ++ ";\n" ++
  "pub const OPERATION_TENSOR_F32_MUL: u32 = " ++ show (operationCode TensorF32Mul) ++ ";\n" ++
  "pub const LAYOUT_DOT: u32 = " ++ show (layoutCode DotLayout) ++ ";\n" ++
  "pub const LAYOUT_MATMUL: u32 = " ++ show (layoutCode MatMulLayout) ++ ";\n" ++
  "pub const LAYOUT_VECTOR: u32 = " ++ show (layoutCode VectorLayout) ++ ";\n" ++
  "pub const LANE_AUTHORITATIVE: u32 = " ++ show (laneCode Authoritative) ++ ";\n" ++
  "pub const LANE_ADVISORY: u32 = " ++ show (laneCode Advisory) ++ ";\n" ++
  "pub const LANE_REMOTE_JOB: u32 = " ++ show (laneCode RemoteJob) ++ ";\n" ++
  "pub const DETERMINISM_ADVISORY_ONLY: u32 = " ++ show (determinismCode AdvisoryOnly) ++ ";\n" ++
  "pub const DETERMINISM_TOLERANCE_BOUNDED: u32 = " ++ show (determinismCode ToleranceBounded) ++ ";\n" ++
  "pub const DETERMINISM_CANONICAL_EXACT: u32 = " ++ show (determinismCode CanonicalExact) ++ ";\n" ++
  "pub const SUPPORT_DECLARED: u32 = " ++ show (supportCode Declared) ++ ";\n" ++
  "pub const SUPPORT_RESILIENT: u32 = " ++ show (supportCode Resilient) ++ ";\n" ++
  "pub const SUPPORT_DETERMINISTIC: u32 = " ++ show (supportCode Deterministic) ++ ";\n" ++
  "pub const SUPPORT_PRODUCTION_SUPPORTED: u32 = " ++ show (supportCode ProductionSupported) ++ ";\n" ++
  "pub const DEVICE_CPU: u32 = " ++ show (deviceCode Cpu) ++ ";\n" ++
  "pub const BACKEND_ZIG_SCALAR: u32 = 1;\n" ++
  "pub const STATUS_OK: u32 = " ++ show (statusCode StatusOk) ++ ";\n" ++
  "pub const STATUS_NULL_POINTER: u32 = " ++ show (statusCode NullPointer) ++ ";\n" ++
  "pub const STATUS_UNSUPPORTED_ABI: u32 = " ++ show (statusCode UnsupportedAbi) ++ ";\n" ++
  "pub const STATUS_UNSUPPORTED_OPERATION_VERSION: u32 = " ++ show (statusCode UnsupportedOperationVersion) ++ ";\n" ++
  "pub const STATUS_UNKNOWN_OPERATION: u32 = " ++ show (statusCode UnknownOperation) ++ ";\n" ++
  "pub const STATUS_INVALID_LANE: u32 = " ++ show (statusCode InvalidLane) ++ ";\n" ++
  "pub const STATUS_INVALID_SUPPORT: u32 = " ++ show (statusCode InvalidSupport) ++ ";\n" ++
  "pub const STATUS_INVALID_DETERMINISM: u32 = " ++ show (statusCode InvalidDeterminism) ++ ";\n" ++
  "pub const STATUS_LAYOUT_MISMATCH: u32 = " ++ show (statusCode LayoutMismatch) ++ ";\n" ++
  "pub const STATUS_LENGTH_MISMATCH: u32 = " ++ show (statusCode LengthMismatch) ++ ";\n" ++
  "pub const STATUS_DIMENSION_OVERFLOW: u32 = " ++ show (statusCode DimensionOverflow) ++ ";\n" ++
  "pub const STATUS_ARITHMETIC_OVERFLOW: u32 = " ++ show (statusCode ArithmeticOverflow) ++ ";\n" ++
  "pub const STATUS_INVALID_RESERVED_FIELD: u32 = " ++ show (statusCode InvalidReservedField) ++ ";\n" ++
  "pub const STATUS_UNSUPPORTED_REQUIREMENT: u32 = " ++ show (statusCode UnsupportedRequirement) ++ ";\n" ++
  "pub const STATUS_INDEX_OUT_OF_RANGE: u32 = " ++ show (statusCode IndexOutOfRange) ++ ";\n" ++
  "pub const STATUS_ALIASING_VIOLATION: u32 = " ++ show (statusCode AliasingViolation) ++ ";\n" ++
  "pub const STATUS_NON_FINITE_INPUT: u32 = " ++ show (statusCode NonFiniteInput) ++ ";\n"

public export
rustDeclarations : String
rustDeclarations =
  "// SPDX-License-Identifier: AGPL-3.0-or-later\n" ++
  "// " ++ generatedNotice ++ "\n\n" ++ codesRust ++ "\n" ++
  "#[repr(C)]\n#[derive(Clone, Copy, Debug)]\npub struct Request {\n" ++
  "    pub abi_major: u16, pub abi_minor: u16, pub operation_major: u16, pub operation_minor: u16,\n" ++
  "    pub operation: u32, pub lane: u32, pub minimum_support: u32, pub minimum_determinism: u32,\n" ++
  "    pub layout: u32, pub reserved: u32, pub dim0: u64, pub dim1: u64, pub dim2: u64,\n}\n" ++
  "#[repr(C)]\n#[derive(Clone, Copy, Debug)]\npub struct BufferI32 { pub data: *const i32, pub len: u64 }\n" ++
  "#[repr(C)]\n#[derive(Debug)]\npub struct BufferI64 { pub data: *mut i64, pub len: u64 }\n" ++
  "#[repr(C)]\n#[derive(Clone, Copy, Debug)]\npub struct BufferF32In { pub data: *const f32, pub len: u64 }\n" ++
  "#[repr(C)]\n#[derive(Debug)]\npub struct BufferF32Out { pub data: *mut f32, pub len: u64 }\n" ++
  "#[repr(C)]\n#[derive(Clone, Copy, Debug, Default)]\npub struct Capability {\n" ++
  "    pub abi_major: u16, pub abi_minor: u16, pub operation_major: u16, pub operation_minor: u16,\n" ++
  "    pub operation: u32, pub support: u32, pub determinism: u32, pub backend_id: u32, pub device_class: u32, pub flags: u32,\n}\n" ++
  "#[repr(C)]\n#[derive(Clone, Copy, Debug, Default)]\npub struct Evidence {\n" ++
  "    pub abi_major: u16, pub abi_minor: u16, pub operation_major: u16, pub operation_minor: u16,\n" ++
  "    pub operation: u32, pub backend_id: u32, pub support: u32, pub determinism: u32,\n}\n" ++
  "unsafe extern \"C\" {\n" ++
  "    pub fn enaction_accel_abi_version() -> u32;\n" ++
  "    pub fn enaction_accel_capability_count() -> u32;\n" ++
  "    pub fn enaction_accel_capability_at(index: u32, out: *mut Capability) -> u32;\n" ++
  "    pub fn enaction_accel_execute(request: *const Request, left: *const BufferI32, right: *const BufferI32, output: *mut BufferI64, evidence: *mut Evidence) -> u32;\n" ++
  "    pub fn enaction_accel_execute_f32(request: *const Request, input: *const BufferF32In, output: *mut BufferF32Out, evidence: *mut Evidence) -> u32;\n" ++
  "    pub fn enaction_accel_execute_f32_binary(request: *const Request, left: *const BufferF32In, right: *const BufferF32In, output: *mut BufferF32Out, evidence: *mut Evidence) -> u32;\n" ++
  "}\n"

public export
juliaDeclarations : String
juliaDeclarations =
  "# SPDX-License-Identifier: AGPL-3.0-or-later\n" ++
  "# " ++ generatedNotice ++ "\n\n" ++
  "module EnactionAcceleratorABI\n\n" ++
  "const ABI_MAJOR = UInt16(" ++ show abiMajor ++ ")\n" ++
  "const ABI_MINOR = UInt16(" ++ show abiMinor ++ ")\n" ++
  "const OPERATION_MAJOR = UInt16(" ++ show operationMajor ++ ")\n" ++
  "const OPERATION_MINOR = UInt16(" ++ show operationMinor ++ ")\n" ++
  "const OPERATION_FIXED_I32_DOT = UInt32(" ++ show (operationCode FixedI32Dot) ++ ")\n" ++
  "const OPERATION_FIXED_I32_MATMUL = UInt32(" ++ show (operationCode FixedI32MatMul) ++ ")\n" ++
  "const OPERATION_TENSOR_F32_RELU = UInt32(" ++ show (operationCode TensorF32Relu) ++ ")\n" ++
  "const OPERATION_TENSOR_F32_RELU6 = UInt32(" ++ show (operationCode TensorF32Relu6) ++ ")\n" ++
  "const OPERATION_TENSOR_F32_MATMUL = UInt32(" ++ show (operationCode TensorF32MatMul) ++ ")\n" ++
  "const OPERATION_TENSOR_F32_ADD = UInt32(" ++ show (operationCode TensorF32Add) ++ ")\n" ++
  "const OPERATION_TENSOR_F32_MUL = UInt32(" ++ show (operationCode TensorF32Mul) ++ ")\n" ++
  "const LAYOUT_VECTOR = UInt32(" ++ show (layoutCode VectorLayout) ++ ")\n" ++
  "const LANE_ADVISORY = UInt32(" ++ show (laneCode Advisory) ++ ")\n" ++
  "const DETERMINISM_TOLERANCE_BOUNDED = UInt32(" ++ show (determinismCode ToleranceBounded) ++ ")\n" ++
  "const SUPPORT_RESILIENT = UInt32(" ++ show (supportCode Resilient) ++ ")\n\n" ++
  "struct Request\n" ++
  "    abi_major::UInt16; abi_minor::UInt16; operation_major::UInt16; operation_minor::UInt16\n" ++
  "    operation::UInt32; lane::UInt32; minimum_support::UInt32; minimum_determinism::UInt32\n" ++
  "    layout::UInt32; reserved::UInt32; dim0::UInt64; dim1::UInt64; dim2::UInt64\n" ++
  "end\n\n" ++
  "struct BufferF32In\n    data::Ptr{Float32}; len::UInt64\nend\n\n" ++
  "struct BufferF32Out\n    data::Ptr{Float32}; len::UInt64\nend\n\n" ++
  "struct Evidence\n" ++
  "    abi_major::UInt16; abi_minor::UInt16; operation_major::UInt16; operation_minor::UInt16\n" ++
  "    operation::UInt32; backend_id::UInt32; support::UInt32; determinism::UInt32\n" ++
  "end\n\n" ++
  "execute_f32(function_pointer::Ptr{Cvoid}, request::Ref{Request}, input::Ref{BufferF32In}, output::Ref{BufferF32Out}, evidence::Ref{Evidence}) =\n" ++
  "    ccall(function_pointer, UInt32, (Ref{Request}, Ref{BufferF32In}, Ref{BufferF32Out}, Ref{Evidence}), request, input, output, evidence)\n\n" ++
  "execute_f32_binary(function_pointer::Ptr{Cvoid}, request::Ref{Request}, left::Ref{BufferF32In}, right::Ref{BufferF32In}, output::Ref{BufferF32Out}, evidence::Ref{Evidence}) =\n" ++
  "    ccall(function_pointer, UInt32, (Ref{Request}, Ref{BufferF32In}, Ref{BufferF32In}, Ref{BufferF32Out}, Ref{Evidence}), request, left, right, output, evidence)\n\n" ++
  "end # module EnactionAcceleratorABI\n"

public export
symbolList : String
symbolList =
  "enaction_accel_abi_version\n" ++
  "enaction_accel_capability_at\n" ++
  "enaction_accel_capability_count\n" ++
  "enaction_accel_execute\n"
  ++ "enaction_accel_execute_f32\n"
  ++ "enaction_accel_execute_f32_binary\n"

private
usage : IO ()
usage = putStrLn "usage: accelerator-abi-gen <c|zig|rust|julia|symbols>"

main : IO ()
main = do
  args <- getArgs
  case args of
    [_, "c"] => putStr cHeader
    [_, "zig"] => putStr zigDeclarations
    [_, "rust"] => putStr rustDeclarations
    [_, "julia"] => putStr juliaDeclarations
    [_, "symbols"] => putStr symbolList
    _ => usage
